### ISSUE TITLE
special abilities get bugged often.

### ISSUE THREAD

**Issue by deadbushpotato23** [Parik27/V.Rainbomizer#30] opened 2021-12-03 10:21 UTC
Hey, the special abilities for each chracter get bugged. Usually they will not fill up or they will be full and wont work at all. Even with randomize special abilities off sometimes micheal will have franklins ability. Certain times micheals ability will work but the when I go into a mission it stops working.

**Comment by Parik27** [comment] 2021-12-14 02:27
If you have the Unused Special Abilities Option enabled (it's disabled by default), you might get some special abilities that are not usable. Other than that, the special abilities should work as intended. Near the start of the game though, not all special abilities are unlocked (as they're unlocked by the missions that unlock a specific character's special ability), so if you get a Michael mission as the second mission, you will not have a working special ability). All characters should have their special abilities unlocked a few missions after the first Heist. 

Special Abilities are not random when you have the option disabled. You might have been confused by the Player Randomizer randomizing Franklin into Michael (so your model is Michael, but the game recognises you as Franklin). I've not come across any instances where the special abilities were random if they weren't supposed to be.

**Comment by deadbushpotato23** [comment] 2021-12-22 15:57
it seems everything was fixed in the new realease yesterday, random special abilities are working as intended.

**Comment by Parik27** [comment] 2021-12-27 09:56
Closing it then. Reopen if you run into this issue again.

**Closed by Parik27** 2021-12-27 09:56 UTC
